# Today I Learned 🤓

> 2024.04.03 (수)

## Exception

프로그램은 항상 에러를 발생시킬 수 있는 가능성을 가지고 있습니다.

개발자가 어떻게 에러를 처리하는지에 따라 프로그램은 더욱 사용자와 개발자에게 친화적인 프로그램이 될 수 있습니다.

오늘은 에러 처리와 관련된 몇 가지 아이디어를 살펴보겠습니다.

<br>

## assert(_:_:file:line:)

> 선택적 메시지로 전통적인 C 스타일 assert 수행하는 메서드
> 
> `iOS 8.0+` `iPadOS 8.0+` `macOS 10.10+`

```swift
func assert(
    _ condition: @autoclosure () -> Bool,
    _ message: @autoclosure () -> String = String(),
    file: StaticString = #file,
    line: UInt = #line
)
```

### 개발 시 에러 체크

assert는 특정 조건을 할당하여, 조건이 성립하지 않으면 메시지를 출력하는 메서드입니다. 

하지만 실제 배포된 앱 성능에는 영향을 주지 않기 때문에 개발 및 내부 테스팅 시 특정 조건을 체크하고 싶을 때 사용할 수 있습니다.

<br>

### 사용자를 위한 에러 메시지

우리가 흔히 LocalizedError를 이용해 구현하는 localizedDescription은 사용자를 위한 에러 메시지가 아닙니다.

하여 error에 따른 사용자 메시지를 제공하고 싶은 경우 UserReadableError와 같은 Protocol을 만들어 userMessage를 구현 및 제공할 수 있습니다.

```swift
protocol UserReadableError: Error {
    var userMessage: String? { get }
}

enum CustomError: UserReadableError {
    case error1
    case error2
    
    var userMessage: String? {
        switch self {
        case .error1, .error2:
            return "다시 시도해 주세요."
        }
    }
}
```

<br>

### 에러 코드 활용

Swift에서 Error는 Protocol이기 때문에 일반적으로 사용하는 Enum 외에도 여러 가지 방법으로 에러를 처리할 수 있습니다.

하여 Enum을 이용하여 case 별로 에러를 제공하는 것이 아닌 Http error와 같이 code와 message를 이용해 에러를 제공 및 처리할 수 있습니다.

```swift
protocol CodeableError: UserReadableError {
    var code: Int { get }
    var message: String { get }
}

struct CustomError: CodeableError {
    var code: Int
    var message: String
    
    var userMessage: String? {
        switch code {
        case 0...99:
            "인터넷 연결을 확인하고 다시 시도해 주세요."
        case 100...199:
            "다시 시도해 주세요."
        default:
            "다시 시도해 주세요. 계속해서 안 될 경우 문의해주세요."
        }
    }
}
```

에러를 던지는 부분에서는 code 및 message를 할당하여 에러를 설정할 수 있습니다.

```swift
func printNumber(_ number: Int?) throws {
    guard let number = number
    else { throw CustomError(code: 404, message: "Number is an optional type.") }
    
    print("number: \(number)")
}

do {
    try printNumber(nil)
} catch {
    let error = error as! CustomError
    print("code: \(error.code), message: \(error.message)")
    print(error.message)
}

// prints "code: 404, message: Number is an optional type."
// prints "다시 시도해 주세요. 계속해서 안 될 경우 문의해주세요."
```

---
## 참고 링크
- [Apple Developer: assert(_:_:file:line:)](https://developer.apple.com/documentation/swift/assert(_:_:file:line:))
